resources:
  layer_1:
    subscribes_to:
      - layer_1
    # restricted_publish_exchanges: []
    default_pathways:
      southbound:
        - layer_2
  layer_2:
    subscribes_to:
      - layer_2
    # restricted_publish_exchanges: []
    default_pathways:
      northbound:
        - layer_1
      southbound:
        - layer_3
  layer_3:
    subscribes_to:
      - layer_3
    # restricted_publish_exchanges: []
    default_pathways:
      northbound:
        - layer_2
      southbound:
        - layer_4
  layer_4:
    subscribes_to:
      - layer_4
    # restricted_publish_exchanges: []
    default_pathways:
      northbound:
        - layer_3
      southbound:
        - layer_5
  layer_5:
    subscribes_to:
      - layer_5
    # restricted_publish_exchanges: []
    default_pathways:
      northbound:
        - layer_4
      southbound:
        - layer_6
  layer_6:
    subscribes_to:
      - layer_6
    # restricted_publish_exchanges: []
    default_pathways:
      northbound:
        - layer_5

exchanges:
  layer_1: {}
  layer_2: {}
  layer_3: {}
  layer_4: {}
  layer_5: {}
  layer_6: {}

queues:
  layer_1: {}
  layer_2: {}
  layer_3: {}
  layer_4: {}
  layer_5: {}
  layer_6: {}

bindings:
  - exchange: layer_1
    queue: layer_1
  - exchange: layer_2
    queue: layer_2
  - exchange: layer_3
    queue: layer_3
  - exchange: layer_4
    queue: layer_4
  - exchange: layer_5
    queue: layer_5
  - exchange: layer_6
    queue: layer_6
